<?php

$fullwidth = array (
    'key' => '57a38f3ad4c9f',
    'name' => 'fullwidth',
    'label' => 'Fullwidth',
    'display' => 'block',
    'sub_fields' => array (
        array (
            'key' => 'field_57a38fbce0b6b',
            'label' => 'Content',
            'name' => 'content',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 1,
        ),
        array (
            'key' => 'field_57a38f9de0b6a',
            'label' => 'Background Image',
            'name' => 'background',
            'type' => 'image',
            'instructions' => '',
            'required' => '',
            'conditional_logic' => '',
            'wrapper' => array (
                'width' => 30,
                'class' => '',
                'id' => '',
            ),
            'return_format' => '',
            'preview_size' => 'thumbnail',
            'library' => '',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '',
        ),
        array (
            'key' => 'field_57a38f62e0b69',
            'label' => 'Class',
            'name' => 'class',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array (
                'width' => 70,
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'section-class another-class',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
            'readonly' => 0,
            'disabled' => 0,
        ),
    ),
    'min' => '',
    'max' => '',
);
